version: "3"

services:

  app:
    image: choieunsoh/learn-12-factors
    build:
      context: .
      args:
        - PORT
        - PASSWORD
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
