name: Deploy to Docker Hub

env:
  NAME: 'Kiattipong Kamonrat'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Print name
        run: echo "Hello, $NAME"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}